name: Build APK (download Gradle)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Show Gradle/Kotlin versions
        run: |
          ./gradlew --version
          echo "KOTLIN_OPTS='$KOTLIN_OPTS'"

      - name: Build debug APK with verbose logs
        env:
          # Make Kotlin compiler very chatty and print full errors
          ORG_GRADLE_PROJECT_kotlin_daemon_debug: "true"
        run: |
          ./gradlew --no-daemon \
            -Dorg.gradle.logging.stacktrace=full \
            -Dorg.gradle.warning.mode=all \
            --stacktrace --info \
            assembleDebug

      - name: Upload APK (if built)
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
