name: Build APK (no wrapper)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Provision Gradle directly (so we can run `gradle ...` without ./gradlew)
      - name: Set up Gradle 8.9
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          cache-read-only: false

      - name: Show layout (debug)
        run: |
          pwd
          ls -la
          echo "----- app -----"
          ls -la app || true
          echo "----- res -----"
          ls -la app/src/main/res || true

      - name: Build debug APK (verbose)
        run: |
          gradle --version
          gradle --no-daemon \
            -Dorg.gradle.logging.stacktrace=full \
            -Dorg.gradle.warning.mode=all \
            --stacktrace --info \
            assembleDebug

      - name: Upload APK
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
