name: Build APK (quiet)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Build (quiet, capture log)
        id: build
        shell: bash
        run: |
          set -o pipefail
          gradle --no-daemon --console=plain -q assembleDebug 2>&1 | tee build.log || echo "BUILD_FAIL" > .fail

      - name: Error digest
        if: ${{ hashFiles('.fail') != '' }}
        shell: bash
        run: |
          echo "===== ERROR DIGEST ====="
          grep -E "^e: |AAPT: error:|resource linking failed|Execution failed for task|AndroidManifest.xml:" -m 80 build.log || true
          echo "----- Last 60 lines -----"
          tail -n 60 build.log || true

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            build.log
          if-no-files-found: warn
